// This file was generated by Firebase Studio
import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-auth-domain",
  "projectId": "mock-project-id",
  "storageBucket": "mock-storage-bucket",
  "messagingSenderId": "mock-messaging-sender-id",
  "appId": "mock-app-id"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export { app, auth, db };
