// This file was generated by Firebase Studio
import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  "projectId": "rideshare-dashboard",
  "appId": "1:199463080893:web:34bb3cdfb65df63cf0b8d4",
  "storageBucket": "rideshare-dashboard.firebasestorage.app",
  "apiKey": "AIzaSyAjKD1WMZbDTPcLX09ZcNrHItIvTTri4II",
  "authDomain": "rideshare-dashboard.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "199463080893"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export { app, auth, db };
